#!/bin/sh

local shell_scripts_dir="$HOME/_scripts/_shell"
local funcs_list=(
    "$shell_scripts_dir/common"
    "$shell_scripts_dir/select_option"
    "$shell_scripts_dir/lcl_uc_frontend"
    # "$shell_scripts_dir/togif"
    # "$shell_scripts_dir/togif_bash"
    # "$shell_scripts_dir/togif_zsh"
)

function source_files() {
    for i in "${funcs_list[@]}"; do
        [[ -f $i ]] && source $i --source-only
    done
}

source_files
